### ISSUE TITLE
Get series currently aired episode

### ISSUE THREAD

**Issue by sachaw** [sachaw/season-tracker#4]
Find and alternate API/method of deriving a given series latest episode number without using the date calculation method used at present.

**Comment by Kingorgg** [comment]
Might be best to use something like the AniList API: 
https://anilist-api.readthedocs.io/en/latest/anime.html#basic

We could also add a countdown for the next episode, as it has the airing times, etc.

You would need to register and setup the API keys though ...

**Comment by sachaw** [comment]
Yea, had a brief look at AniList's API, just one question, is there ID's match Hummingbird's?

**Comment by Kingorgg** [comment]
Looks like it uses Mal ID numbers, which you can get from Hummingbird API by using `mal_id`

**Comment by sachaw** [comment]
Good, that'l b easy then, ill start work on an api hook for it tonight

**Comment by sachaw** [comment]
Have started working with the API but ran into an issue have posted an issue here: https://github.com/joshstar/AniList-API-Docs/issues/106 as soon as I get a reply, I will continue.

**Comment by joshstar** [comment]
Just a note here that AniList has its own unique IDs, some of them happen the match that of mals but a large majority do not.

**Comment by sachaw** [comment]
thanks for the info @joshstar do you know of any way to match the two items or any other service that would meed our needs, thanks again.

**Comment by joshstar** [comment]
Not really I'm afraid. You could try to match them with titles and then record the ids for each service you use but that will have a lot of issues. Its possible someone else has done something similar and has the ids for multiple services already, but again unless they've carefully checked each id is correct you'll get some entries that don't match up correctly.

**Comment by sachaw** [comment]
Alright, ill look into some solutions in the morning.

**Comment by sachaw** [comment]
Working on a set of api relation functions I'll push in a while
